include(FindPackageHandleStandardArgs)

find_path(JPEGXL_INCLUDE_DIR jxl/version.h)
find_library(JPEGXL_LIBRARY NAMES jxl)

find_package_handle_standard_args(
    JPEGXL
    REQUIRED_VARS JPEGXL_LIBRARY JPEGXL_INCLUDE_DIR
    HANDLE_COMPONENTS
)

if(JPEGXL_FOUND AND NOT TARGET JPEGXL::JPEGXL)
    add_library(JPEGXL::JPEGXL UNKNOWN IMPORTED)
    set_target_properties(JPEGXL::JPEGXL PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${JPEGXL_INCLUDE_DIR}")
    set_target_properties(
        JPEGXL::JPEGXL PROPERTIES IMPORTED_LINK_INTERFACE_LANGUAGES "CXX" IMPORTED_LOCATION "${JPEGXL_LIBRARY}"
    )
endif()

mark_as_advanced(JPEGXL_LIBRARY JPEGXL_INCLUDE_DIR)
